version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-todo-db
    environment:
      MYSQL_ROOT_PASSWORD: root@1234
      MYSQL_DATABASE: todo
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo@1234
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - todo-network

  backend:
    build:
      context: ./todo-backend
    ports:
      - "8080:8080"
    networks:
      - todo-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/todo
      - SPRING_DATASOURCE_USERNAME=todo_user
      - SPRING_DATASOURCE_PASSWORD=todo@1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  frontend:
    build:
      context: ./todo-frontend
    ports:
      - "3000:80"
    networks:
      - todo-network
    depends_on:
      - backend

volumes:
  db-data:

networks:
  todo-network: