spring:
  application:
    name: todo
  datasource:
    url: jdbc:mysql://localhost:3307/todo
    username: todo_user
    password: todo@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect